left_separator: "  "
script_dir: "/home/frederik/bin/dwmblocks/status"
segments:
    - script: "volume"
      signals: [1]

    - script: "mail"
      update_interval: 60
      signals: [4]

    - script: "nordvpn"
      update_interval: 60
      hide_if_empty: true

    - script: "battery"
      update_interval: 10
      hide_if_empty: true

    - script: "internet"
      update_interval: 10
      hide_if_empty: true

    - program: "date"
      args: ["+%a. %d. %B %Y"]
      update_interval: 60
      icon: "  "

    - program: "date"
      args: ["+%H:%M"]
      update_interval: 60
      icon: " "
